[functions.generate-ai-posts]
enabled = true
verify_jwt = false
import_map = "./functions/generate-ai-posts/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-ai-posts/posts.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-ai-posts/*.html" ]

[functions.generate-bot-replies]
enabled = true
verify_jwt = false
import_map = "./functions/generate-bot-replies/deno.json"
entrypoint = "./functions/generate-bot-replies/replies.ts"

[functions.generate-bot-reactions]
enabled = true
verify_jwt = false
import_map = "./functions/generate-bot-reactions/deno.json"
entrypoint = "./functions/generate-bot-reactions/reactions.ts"

[functions.Generate-Events]
enabled = true
verify_jwt = false
import_map = "./functions/Generate-Events/deno.json"
entrypoint = "./functions/Generate-Events/index.ts"

[functions.swift-api]
enabled = true
verify_jwt = false
import_map = "./functions/swift-api/deno.json"
entrypoint = "./functions/swifft-api/index.ts"