name: Deploy Website to InfinityFree

on:
  push:
    branches:
      - main 

jobs:
  web-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Sync files to server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        local-dir: ./
        server-dir: ./htdocs/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.github/**
